"""add dia_folga to colaboradores

Revision ID: 96c6f3eed497
Revises: 19ef2f8b401a
Create Date: 2026-07-22 09:08:26.067522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c6f3eed497'
down_revision: Union[str, Sequence[str], None] = '19ef2f8b401a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colaboradores', sa.Column('dia_folga', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('colaboradores', 'dia_folga')
    # ### end Alembic commands ###
